detectors:
  DuplicateMethodCall:
    exclude:
      - RSpec::RedisHelper#with_clean_redis
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    exclude:
      - AuthenticateComputer::App#normalize_url

exclude_paths:
  - vendor/
