require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Exclude:
    - lib/authenticate_computer/app.rb

Metrics/LineLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/DescribeMethod:
  Enabled: false

RSpec/FilePath:
  IgnoreMethods: true

RSpec/MultipleExpectations:
  Max: 3

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
