require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

RSpec/DescribeMethod:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
