require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
