name: CI

on:
  push:
    branches-ignore: [production]
  pull_request:
    branches-ignore: [production]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: ruby
      - uses: github/codeql-action/analyze@v2
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run bundler-audit
        run: bundle exec bundle-audit check --update
  lint:
    name: Lint
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop --require code_scanning --format progress --format CodeScanning::SarifFormatter --out rubocop.sarif
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: rubocop.sarif
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2.3-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec --format RSpec::Github::Formatter
        env:
          COOKIE_NAME: _authenticate_computer
          COOKIE_SECRET: 29c22ff1e8978a2e0a0b7f9a5a2c025034f042a7cc83c055
          REDIS_URL: redis://localhost:6379
